Map server commands
calmilamsy/biny-mappings pull request #24
Opened 2024-04-21 00:22 UTC by Goodlyay

Re-opening on another branch this time.
Mapped classes directly related to server commands.

2024-04-23 16:09 UTC, DanyGames2014 requested changes

2024-04-23 16:09 UTC, DanyGames2014 commented on mappings/net/minecraft/CommandDispatcher.mapping
> +CLASS net/minecraft/class_39 net/minecraft/CommandDispatcher
This isn't in any package, would expect it to be in some kind of `net.minecraft.server.command` package

2024-04-23 16:09 UTC, DanyGames2014 commented on mappings/net/minecraft/server/Command.mapping
> +	FIELD field_160 commandDispatcher Lnet/minecraft/class_39;
[dispatcher](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/server/command/CommandManager.html#dispatcher) in yarn

2024-04-23 16:09 UTC, DanyGames2014 commented on mappings/net/minecraft/server/Command.mapping
> +	METHOD <init> (Ljava/lang/String;Lnet/minecraft/class_39;)V
Would be good to also map argument 2 as dispatcher while you're here
![obrazek](https://github.com/calmilamsy/biny-mappings/assets/24621316/71c2d61c-10af-4159-bced-a6f69471494a)

2024-04-23 16:09 UTC, DanyGames2014 commented on mappings/net/minecraft/server/ServerCommandHandler.mapping
> +	FIELD field_1687 minecraftServer Lnet/minecraft/server/MinecraftServer;
should be server (viz. discord convo)

2024-04-23 16:09 UTC, DanyGames2014 commented on mappings/net/minecraft/server/ServerCommandHandler.mapping
> +		ARG 1 minecraftServer
should be server (viz. discord convo)

2024-04-23 16:09 UTC, DanyGames2014 commented on mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
> +	FIELD field_919 minecraftServer Lnet/minecraft/server/MinecraftServer;
should be server (viz. discord convo)

2024-04-23 16:09 UTC, DanyGames2014 commented on mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
> +	FIELD field_920 serverPlayerEntity Lnet/minecraft/class_69;
[player](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/server/network/ServerPlayNetworkHandler.html#player) in yarn

2024-04-23 16:09 UTC, DanyGames2014 commented on mappings/net/minecraft/server/ServerCommandHandler.mapping
> +		ARG 1 intString
probably only [string](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/util/math/MathHelper.html#parseInt(java.lang.String,int)) in yarn, seems like the method has understandably been moved to MathHelper

2024-04-23 17:01 UTC, calmilamsy requested changes
Otherwise, looks good at a glance.

2024-04-23 17:01 UTC, calmilamsy commented on mappings/net/minecraft/server/command/Command.mapping
> +	FIELD field_159 message Ljava/lang/String;
Not 100% on this, but my only suggestion is perhaps `commandText` instead, considering it cuts the `/` from the start, so it's not the whole message.

2024-04-23 17:01 UTC, calmilamsy commented on mappings/net/minecraft/server/command/CommandDispatcher.mapping
> +CLASS net/minecraft/class_39 net/minecraft/server/command/CommandDispatcher
This should be `CommandOutput`. This doesn't handle command logic, and simply logs and provides user feedback. Took a bit of poking around to figure this out.

2024-04-23 17:01 UTC, calmilamsy commented on mappings/net/minecraft/server/command/ServerCommandHandler.mapping
> +	METHOD method_1411 executeCommand (Lnet/minecraft/class_38;)V
On an unrelated note: I regret looking at this method.

2024-04-23 17:01 UTC, DanyGames2014 approved these changes

2024-04-23 17:03 UTC, DanyGames2014 commented on mappings/net/minecraft/server/command/ServerCommandHandler.mapping
> +	METHOD method_1411 executeCommand (Lnet/minecraft/class_38;)V
Yeah me too, no wonder they rewrote pretty much the entire thing 😭

2024-04-23 17:51 UTC, Goodlyay commented on mappings/net/minecraft/server/command/ServerCommandHandler.mapping
> +	METHOD method_1411 executeCommand (Lnet/minecraft/class_38;)V
I also regretted looking at this method

2024-04-23 17:59 UTC, Goodlyay commented on mappings/net/minecraft/server/command/Command.mapping
> +	FIELD field_159 message Ljava/lang/String;
A bit verbose but commandAndArgs maybe? I can't think of anything else that makes it more clear what it is

2024-04-27 16:04 UTC, calmilamsy approved these changes
I'm happy with these names.

2024-04-28 19:36 UTC, merged