Mapping path stuff for entities
calmilamsy/biny-mappings pull request #31
Opened 2024-05-15 21:01 UTC by matthewperiut

Pretty hard to match up with modern yarn bc its very different but i think this is just enough mapped to make doing the things I do with entities easier.

2024-06-11 09:19 UTC, DanyGames2014 requested changes
I apologize for the nuke I dropped

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/Path.mapping
> +	FIELD field_2692 currentIndex I
[currentNodeIndex](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/Path.html#currentNodeIndex) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/Path.mapping
> +	METHOD method_2040 incrementIndex ()V
[next](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/Path.html#next()) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/Path.mapping
> +	METHOD method_2042 isComplete ()Z
[isFinished](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/Path.html#isFinished()) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/Path.mapping
> +	METHOD method_2043 getLastPathNode ()Lnet/minecraft/class_29;
[getEnd](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/Path.html#getEnd()) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/Path.mapping
> +	METHOD method_2041 getCurrentPosition (Lnet/minecraft/class_57;)Lnet/minecraft/class_26;
[getCurrentNodePos](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/Path.html#getCurrentNodePos()) in Yarn, but I would opt for the full `getCurrentNodePosition` since its the only method which actually retrieves any position so it makes sense to be a bit more descriptive

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	FIELD field_149 uniqueId I
[hashCode](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNode.html#hashCode) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	METHOD method_114 distanceTo (Lnet/minecraft/class_29;)F
[getDistance](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNode.html#getDistance(net.minecraft.entity.ai.pathing.PathNode)) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	METHOD method_113 computeIndex (III)I
[hash](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNode.html#hash(int,int,int)) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	FIELD field_143 parentIndex I
[heapIndex](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNode.html#heapIndex) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	METHOD method_112 isInitialized ()Z
[isInHeap](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNode.html#isInHeap()) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +CLASS net/minecraft/class_108 net/minecraft/entity/ai/pathing/MobNavigation
[PathNodeNavigator](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNodeNavigator.html) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodePriorityQueue.mapping
> +CLASS net/minecraft/class_109 net/minecraft/entity/ai/pathing/PathNodePriorityQueue
[PathMinHeap](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathMinHeap.html) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodePriorityQueue.mapping
> +CLASS net/minecraft/class_109 net/minecraft/entity/ai/pathing/PathNodePriorityQueue
field_931 is pathNodes
field_932 is count

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodePriorityQueue.mapping
> +	METHOD method_843 enqueueNode (Lnet/minecraft/class_29;)Lnet/minecraft/class_29;
[push](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathMinHeap.html#push(net.minecraft.entity.ai.pathing.PathNode)) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodePriorityQueue.mapping
> +	METHOD method_843 enqueueNode (Lnet/minecraft/class_29;)Lnet/minecraft/class_29;
first arg is node

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodePriorityQueue.mapping
> +	METHOD method_841 clearQueue ()V
[clear](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathMinHeap.html#clear()) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodePriorityQueue.mapping
> +	METHOD method_845 popNode ()Lnet/minecraft/class_29;
[pop](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathMinHeap.html#pop()) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodePriorityQueue.mapping
> +	METHOD method_842 bubbleUp (I)V
[shiftUp](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathMinHeap.html#shiftUp(int)) in Yarn

first arg is index

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodePriorityQueue.mapping
> +	METHOD method_846 sinkDown (I)V
[shiftDown](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathMinHeap.html#shiftDown(int)) in Yarn

first arg is index

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodePriorityQueue.mapping
> +	METHOD method_844 updateNodeCost (Lnet/minecraft/class_29;F)V
[setNodeWeight](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathMinHeap.html#setNodeWeight(net.minecraft.entity.ai.pathing.PathNode,float)) 

first arg is node
second arg is weight

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	FIELD field_144 costG F
penalizedPathLength in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	FIELD field_145 costH F
distanceToNearestTarget in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	FIELD field_146 costF F
heapWeight in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +	FIELD field_334 pathNodePriorityQueue Lnet/minecraft/class_109;
[minHeap](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNodeNavigator.html#minHeap) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +	FIELD field_336 nodes [Lnet/minecraft/class_29;
[successors](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNodeNavigator.html#successors) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +	METHOD method_406 navigatePath (Lnet/minecraft/class_57;Lnet/minecraft/class_29;Lnet/minecraft/class_29;Lnet/minecraft/class_29;F)Lnet/minecraft/class_61;
[findPathToAny](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNodeNavigator.html#findPathToAny(net.minecraft.util.profiler.Profiler,net.minecraft.entity.ai.pathing.PathNode,java.util.Map,float,int,float)) in Yarn

arg2 startNode

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +	METHOD method_401 reconstructPath (Lnet/minecraft/class_29;Lnet/minecraft/class_29;)Lnet/minecraft/class_61;
*maybe* [createPath](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNodeNavigator.html#createPath(net.minecraft.entity.ai.pathing.PathNode,net.minecraft.util.math.BlockPos,boolean)) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	FIELD field_147 parentNode Lnet/minecraft/class_29;
previous in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
> +	FIELD field_148 isClosed Z
visited in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +	METHOD method_402 findPath (Lnet/minecraft/class_57;DDDF)Lnet/minecraft/class_61;
[findPathToAny](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/entity/ai/pathing/PathNodeNavigator.html#findPathToAny(net.minecraft.world.chunk.ChunkCache,net.minecraft.entity.mob.MobEntity,java.util.Set,float,int,float)) in Yarn

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +	METHOD method_403 findPathToLocation (Lnet/minecraft/class_57;IIIF)Lnet/minecraft/class_61;
same as findPathToEntity with the consistency, but even if the name stays it should probably be named `findPathToPosition` as position is used more to represent coords

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +	METHOD method_407 findPathToEntity (Lnet/minecraft/class_57;Lnet/minecraft/class_57;F)Lnet/minecraft/class_61;
might be worth considering this to be findPathToAny for consistency with Yarn where all the methods to findPath have the same name, but at the same time I think that this better represents its function

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +	METHOD method_400 getPathNode (III)Lnet/minecraft/class_29;
*looks like* [PathNodeMaker](https://maven.fabricmc.net/docs/yarn-1.20.6+build.3/net/minecraft/entity/ai/pathing/PathNodeMaker.html#getNode(net.minecraft.util.math.BlockPos)) in Yarn

this leads me to believe that PathNodeMaker and PathNodeNavigator used to be a single class

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
> +	FIELD field_335 pathNodeMap Lnet/minecraft/class_80;
I think that this is pathNodeCache which mightve been replaced by the usage of Int2ObjectMap

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +CLASS net/minecraft/class_80 net/minecraft/entity/ai/pathing/PathNodeMap
I think that this is pathNodeCache as seen in PathNodeNavigator which mightve been replaced by the usage of Int2ObjectMap from fastutil, the comments on this class will then be to match it closer to the Int2ObjectMap as seen in modern, this **SHOULD** very much be discussed as im heading into the game theory terriority here, but the prior possible existence of PathNodeNavigator and PathNodeMaker as a single class and the very specific usage of this class leads me to believe that im atleast on the right path

I think that the name PathNodeCache would be fitting

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +	METHOD method_771 clearMap ()V
clear

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +	METHOD method_772 putNode (I)Ljava/lang/Object;
put(key)

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +	METHOD method_775 putNode (ILjava/lang/Object;)V
put(key, value)

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +	METHOD method_779 removeNode (I)Ljava/lang/Object;
remove(key)

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +	METHOD method_777 containsNode (I)Z
containsKey(key)

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +	METHOD method_774 internalPutNode (IILjava/lang/Object;I)V
internalPut

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +	METHOD method_780 internalRemoveNode (I)Lnet/minecraft/class_232;
internalRemove(key)

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +	METHOD method_778 getInternalNode (I)Lnet/minecraft/class_232;
get(key)

or is there a reason this is marked as internal ?

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/entity/ai/pathing/PathNodeMap.mapping
> +CLASS net/minecraft/class_80 net/minecraft/entity/ai/pathing/PathNodeMap
field_860 is probably size

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/world/World.mapping
> +	METHOD method_189 findPathToLocation (Lnet/minecraft/class_57;IIIF)Lnet/minecraft/class_61;
this should probably be `findPathToPosition` for same reason as in PathNodeNavigator, altho [findPathTo](https://maven.fabricmc.net/docs/yarn-1.20.6+build.3/net/minecraft/entity/ai/pathing/EntityNavigation.html#findPathTo(net.minecraft.util.math.BlockPos,int)) might be better

2024-06-11 09:19 UTC, DanyGames2014 commented on mappings/net/minecraft/world/World.mapping
> +	METHOD method_192 findPathToEntity (Lnet/minecraft/class_57;Lnet/minecraft/class_57;F)Lnet/minecraft/class_61;
[findPathTo](https://maven.fabricmc.net/docs/yarn-1.20.6+build.3/net/minecraft/entity/ai/pathing/EntityNavigation.html#findPathTo(net.minecraft.entity.Entity,int)) might be closer match

2024-07-08 10:15 UTC, matthewperiut commented
superceded by #35

2024-07-08 10:15 UTC, closed without merging