Map EntityRenderDispatcher
calmilamsy/biny-mappings pull request #37
Opened 2024-07-11 17:11 UTC by matthewperiut

2024-08-13 08:35 UTC, DanyGames2014 requested changes

2024-08-13 08:35 UTC, DanyGames2014 commented on mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
> +	METHOD method_2032 cleanUp (Lnet/minecraft/class_57;DDDFF)V
This appears to be more of a `postRender` method

2024-08-13 08:35 UTC, DanyGames2014 commented on mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
> +	FIELD field_2496 livingEntity Lnet/minecraft/class_127;
this is the camera entity. So matching it to [camera](https://maven.fabricmc.net/docs/yarn-1.21.1+build.3/net/minecraft/client/particle/ParticleManager.html#addBlockBreakParticles(net.minecraft.util.math.BlockPos,net.minecraft.block.BlockState)) would make it `cameraEntity`

2024-08-20 08:05 UTC, DanyGames2014 approved these changes

2024-09-03 13:18 UTC, calmilamsy approved these changes

2024-09-03 13:18 UTC, merged