InteractionManagers
calmilamsy/biny-mappings pull request #40
Opened 2024-07-27 20:35 UTC by danilwhale

Finishes mapping of `*InteractionManager` and adds `TestInteractionManager`

2024-08-13 07:45 UTC, DanyGames2014 requested changes

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/client/InteractionManager.mapping
> +	METHOD method_1707 interactBlock (IIII)V
[attackBlock](https://maven.fabricmc.net/docs/yarn-1.21.1+build.3/net/minecraft/client/network/ClientPlayerInteractionManager.html#attackBlock(net.minecraft.util.math.BlockPos,net.minecraft.util.math.Direction)) in Yarn

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/client/InteractionManager.mapping
> +	METHOD method_1705 resetBlockBreaking ()V
[cancelBlockBreaking](https://maven.fabricmc.net/docs/yarn-1.21.1+build.3/net/minecraft/client/network/ClientPlayerInteractionManager.html#cancelBlockBreaking()) in Yarn

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/client/InteractionManager.mapping
> +	METHOD method_1709 onContainerRemove (ILnet/minecraft/class_54;)V
Container is ScreenHandler in BINY. Altho this is called purely from HandledScreen, not ScreenHandler so something like `onScreenRemoved(syncId, player)`  would be more accurate

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/client/InteractionManager.mapping
>  		ARG 1 windowId
While this isnt part of the PR, it feels fitting to correct this to syncId while we are here

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/client/InteractionManager.mapping
> +	METHOD method_1713 interactBlockWithItem (Lnet/minecraft/class_54;Lnet/minecraft/class_18;Lnet/minecraft/class_31;IIII)Z
[interactBlock](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/server/network/ServerPlayerInteractionManager.html#interactBlock(net.minecraft.server.network.ServerPlayerEntity,net.minecraft.world.World,net.minecraft.item.ItemStack,net.minecraft.util.Hand,net.minecraft.util.hit.BlockHitResult)) in Yarn

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/client/InteractionManager.mapping
> +	METHOD method_1721 onBlockBreakingAction (IIII)V
[processBlockBreakingAction](https://maven.fabricmc.net/docs/yarn-1.20-pre4+build.2/net/minecraft/server/network/ServerPlayerInteractionManager.html#processBlockBreakingAction(net.minecraft.util.math.BlockPos,net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.Action,net.minecraft.util.math.Direction,int,int)) in Yarn

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/MultiplayerInteractionManager.mapping
> +	FIELD field_2608 miningPosX I
maybe `breakingPosX` so we have a consistent terminology and dont switch between mining and breaking (like yarn (: ), technically `currentBreakingPosX` would be the closest in that case, but that feels obscenely long. Block breaking feels more appropriate then mining imo

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/MultiplayerInteractionManager.mapping
> +	FIELD field_2609 miningPosY I
Same comment as miningPosX

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/MultiplayerInteractionManager.mapping
> +	FIELD field_2610 miningPosZ I
Same comment as miningPosX

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/MultiplayerInteractionManager.mapping
> +	FIELD field_2613 miningSoundDelayTicks F
Same comment as miningPosX

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/MultiplayerInteractionManager.mapping
> +	FIELD field_2614 miningDelayTicks I
Same comment as miningPosX

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/MultiplayerInteractionManager.mapping
> +	FIELD field_2615 mining Z
Same comment as miningPosX.  `breakingBlock` would be the closest

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/SingleplayerInteractionManager.mapping
> +	FIELD field_2181 miningPosX I
Same as MultiplayerInteractionManager

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/SingleplayerInteractionManager.mapping
> +	FIELD field_2182 miningPosY I
Same as MultiplayerInteractionManager

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/SingleplayerInteractionManager.mapping
> +	FIELD field_2183 miningPosZ I
Same as MultiplayerInteractionManager

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/SingleplayerInteractionManager.mapping
> +	FIELD field_2186 miningSoundDelayTicks F
Same as MultiplayerInteractionManager

2024-08-13 07:45 UTC, DanyGames2014 commented on mappings/net/minecraft/SingleplayerInteractionManager.mapping
> +	FIELD field_2187 miningDelayTicks I
Same as MultiplayerInteractionManager

2024-08-13 11:04 UTC, DanyGames2014 approved these changes
Vincent, we happy?
Yeah, we're happy

2024-08-17 19:29 UTC, matthewperiut commented
It seems that the javadoc lint task fails due to something in this commit, see log:
```
> Task :javadocLint FAILED
lint: net/minecraft/screen/ScreenHandlerListener.onPropertyUpdate(Lnet/minecraft/class_71;II)V.syncId: parameter javadoc ends with '.'
lint: net/minecraft/screen/ScreenHandlerListener.onPropertyUpdate(Lnet/minecraft/class_71;II)V.syncId: parameter javadoc starts with uppercase word 'Arbitrary'
lint: net/minecraft/screen/ScreenHandlerListener.onPropertyUpdate(Lnet/minecraft/class_71;II)V.trackedValue: parameter javadoc ends with '.'
lint: net/minecraft/screen/ScreenHandlerListener.onPropertyUpdate(Lnet/minecraft/class_71;II)V.trackedValue: parameter javadoc starts with uppercase word 'This'
```

Apparently, these are considered (later in the log it says) javadoc format errors:
```
 What went wrong:
Execution failed for task ':javadocLint'.
 A failure occurred while executing net.fabricmc.filament.task.JavadocLintTask$LintAction
    Found 4 javadoc format errors! See the log for details.
```

2024-08-20 08:06 UTC, calmilamsy requested changes
Please fix the javadoc issues.

2024-08-20 17:30 UTC, matthewperiut commented
gg javadoc issue was mine, sorry about that guys

2024-08-21 15:03 UTC, calmilamsy approved these changes
Javadoc was unrelated to this PR, merging.

2024-08-21 15:03 UTC, merged