Map ServerPlayerInteractionManager
calmilamsy/biny-mappings pull request #49
Opened 2024-09-17 17:41 UTC by matthewperiut

Directly named and mapped to https://maven.fabricmc.net/docs/yarn-1.21.1+build.3/net/minecraft/server/network/ServerPlayerInteractionManager.html
Methods, variables, and their functions are identical.
Everything in this PR should match the yarn names including the slight adjustment to ServerPlayerEntity.

2024-09-17 20:05 UTC, KydZombie requested changes
fix interactItem's name and remove pos from the position variables since they already have x, y, or z in their names

2024-09-17 20:05 UTC, KydZombie commented on mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
> +	METHOD method_1831 iteractItem (Lnet/minecraft/class_54;Lnet/minecraft/class_18;Lnet/minecraft/class_31;)Z
interactItem

2024-09-17 20:05 UTC, KydZombie commented on mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
> +	FIELD field_2313 failedMiningPosX I
should probably just be failedMiningX instead of PosX, same for others

2024-09-17 20:06 UTC, matthewperiut commented on mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
> +	METHOD method_1831 iteractItem (Lnet/minecraft/class_54;Lnet/minecraft/class_18;Lnet/minecraft/class_31;)Z
i can spell

2024-09-17 23:51 UTC, KydZombie approved these changes

2024-09-18 13:51 UTC, calmilamsy approved these changes

2024-09-18 13:51 UTC, merged